name: roads
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.8
  - cudatoolkit=10.2
  - torchvision
  - matplotlib
  - numpy
  - pip
  - py-opencv=3.4.9
  - pip:
    - dvc
    - mlflow

